### ISSUE TITLE
Open notebooks/senators.pickle issue

### ISSUE THREAD

**Issue by Qing999** [neelsomani/senator-filings#4]
Hi,
i get an Erro on line 184
[Errno 2] No such file or directory: 'notebooks/senators.pickle'

It doesn't seem to be possible to open the file under windows

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    senator_txs = main()
    LOGGER.info('Dumping to .pickle')
    **with open('notebooks/senators.pickle', 'wb') as f:**
        pickle.dump(senator_txs, f)

**Comment by neelsomani** [comment]
Hi @Qing999, could you check your Python version? If I had to make a guess, I think you might be using python2, but the project is built for python3.

**Comment by Qing999** [comment]
@neelsomani  
unfortunately that cannot be the issue.
I actually use python 3.8

**Comment by neelsomani** [comment]
Would it be possible for you to figure out what syntax for this works on your machine:

```with open('notebooks/senators.pickle', 'wb') as f:```

**Comment by Qing999** [comment]
@neelsomani 
i used the direct path, then it worked:
with open(r 'C:\Users\...\...\pickletest.pickle', 'wb') as f:

But i have another problem at the Senator Filings Analysis file.
### 13:
returns = pd.DataFrame(senator_returns)
returns = returns[(returns['tx_total_return'] > returns['tx_cagr'])
                  & (returns['tx_cagr'] > 0)]
returns.sort_values('tx_cagr')

### Error:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
C:\Python38\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2645             try:
-> 2646                 return self._engine.get_loc(key)
   2647             except KeyError:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'tx_total_return'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
 in 
      1 returns = pd.DataFrame(senator_returns)
----> 2 returns = returns[(returns['tx_total_return'] > returns['tx_cagr'])
      3                   & (returns['tx_cagr'] > 0)]
      4 returns.sort_values('tx_cagr')

C:\Python38\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2798             if self.columns.nlevels > 1:
   2799                 return self._getitem_multilevel(key)
-> 2800             indexer = self.columns.get_loc(key)
   2801             if is_integer(indexer):
   2802                 indexer = [indexer]

C:\Python38\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2646                 return self._engine.get_loc(key)
   2647             except KeyError:
-> 2648                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2649         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2650         if indexer.ndim > 1 or indexer.size > 1:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'tx_total_return'

### 14:
plot_senator_growth(senator_tx_growth['Angus S King, Jr.'])

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
 in 
----> 1 plot_senator_growth(senator_tx_growth['Angus S King, Jr.'])

KeyError: 'Angus S King, Jr.'

**Comment by neelsomani** [comment]
Just to be clear, are these two separate errors?

First error: What does your `returns` DataFrame look like? Maybe check to make sure your version of pandas matches the `requirements.txt` file.

Second error: What keys are present in `senator_tx_growth`? Does the `senators_tx` DataFrame contain roughly the correct number of rows (about 10,000)?

**Comment by neelsomani** [comment]
Hi @Qing999, let me know if you're still having issues with the latest version of the repo. Closing this issue in the meantime!
